DROP TABLE IF EXISTS reviews;

CREATE TABLE reviews(
    review_text text,
    num_helpful_votes int,
    link text,
    hotel_name text,
    locality text
);

INSERT INTO reviews 
            VALUE('Stayed in a king suite for 11 nights and yes it cots us a bit but we were happy with the standard of room, the location and the friendliness of the staff. Our room was on the 20th floor overlooking Broadway and the madhouse of the Fairway Market. Room was quite with no noise evident from the hallway or adjoining rooms. It was great to be able to open windows when we craved fresh rather than heated air. The beds, including the fold out sofa bed, were comfortable and the rooms were cleaned well. Wi-fi access worked like a dream with only one connectivity issue on our first night and this was promptly responded to with a call from the service provider to ensure that all was well. The location close to the 72nd Street subway station is great and the complimentary umbrellas on the drizzly days were greatly appreciated. It is fabulous to have the kitchen with cooking facilities and the access to a whole range of fresh foods directly across the road at Fairway.
This is the second time that members of the party have stayed at the Beacon and it will certainly be our hotel of choice for future visits.', 0, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('On every visit to NYC, the Hotel Beacon is the place we love to stay. So conveniently located to Central Park, Lincoln Center and great local restaurants. The rooms are lovely - beds so comfortable, a great little kitchen and new wizz bang coffee maker. The staff are so accommodating and just love walking across the street to the Fairway supermarket with every imaginable goodies to eat (if you choose not to go out for every meal!)', 0, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('Loved the hotel. Great location - only 2 blocks from 72nd St subway. We had a 1 bedroom suite on the 24th floor and had a wonderful view of the Hudson River and the upper West Side. Lovely subtle green decor and room large for NYC standards. It was great having the living area with the lounge that converted into a double bed for our 2 children (12 and 14). Kitchenette was handy to eat breakfast in. We did cook a few evening meals but were limited with cutlery! The Fairway market across the road from the hotel was fabulous. It had an amazing variety of produce as well as ready cooked meals. Having the laundry on the 7th floor was extremely handy. US$1.75 per load and you could get change from the front reception. The staff and front doormen were all very friendly and helpful. Next to the lift is an info desk where you could get a map of NYC. We used this map for the subway, streets and main attractions as these were all on it. Good bottle shop next door to hotel as well.', 0, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('Our first stay on the upper west side and can''t say enough good things about the Hotel Beacon. We stayed here based on reviews of family friendly hotels. I''m not sure exactly how they are more family friendly than any other hotel except for the suites and kitchenettes for budget-conscious families. There weren''t any special programs for kids, but we did see other families there. For NYC, a nice sized Queen suite gave us everything we needed. Didn''t use the kitchen for our overnight stay but definitely would in the future. Rooms were comfortable (ok... a little tight at the foot of the bed but not like some complaints described), the amenities were really appreciated, e.g., free wifi, Keurig coffee service in room, desk area, energy efficient rooms (you put your room card in a device that controls the electricity to save energy while you''re out). Lovely bathrooms (although they need a hand towel holder), but really comfortable. We are a family of 3 so the kiddo slept on the pull-out sofa. Room was in good condition-- it appears that shade of green must be the theme, but its nice. The bellman held our luggage after checkout to allow us to stay in the city and not have to worry about our bags. Parking garage is right around the corner -- very close. Viand diner downstairs was OK for dinner -- not great but sufficient. Friendly front desk folks were really helpful -- have breakfast at Bagel Talk not too far away. Very convenient to American Museum of Natural History -- easy to catch a cab or subway. We will definitely stay here again and very happy to recommend.', 0, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('Great room, very big with huge bed! Great location, just one block''s walk from 72nd subway then 5 minute ride to Times Square and anywhere you want to go from there!
We had a room on the 24th floor so great views of San Remo building and Central Park but building sways ALOT in windy weather, very weird at first!
Very close to Central Park, check out Cafe Viand for sit down breakfast and Fairway and Levain Bakery for take away breakfast.
Great all in all!', 0, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('We stayed at this property in October for a week. Had a king suite, which really was a suite, with sitting room/kitchenette, bedroom and bath. The room was at the rear of the building, which might have been a problem on lower floors (the air shaft was below us); however, we were on the 10th floor and had a decent view to the east, overlooking rooftops. Television in both rooms. The staff was very friendly and helpful. The market across the street was handy for breakfast items and snacks. Only a couple short blocks to the 72nd Street subway.station, where you can pick up the 1,2 and 3 trains. We had previously stayed at a hotel further north, but, nice as it was (with accompanying prices), it cannot compare with the Beacon for value. Definitely recommended.', 0, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('We go to New York every year and this is where we stay every time. The people who work here are so friendly! The hotel is beautiful and clean. It is always very quiet. I love that there is a market across the street and there are many great places to eat and have drinks nearby!', 0, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('We stayed in the Hotel Beacon for a week in late October and found it to be a very good hotel.
The rooms are very large - we were on the tenth floor - and had a kitchenette/lounge and a bedroom and three walk-in wardrobes !! The staff were very friendly and helpful, and the location was great - handy to central park - a short walk down to the Hudson - the 72nd street train station was just a short walk away... and the best feature of the area was the "Fairway Market" - everything you could want in the way of food/groceries/drink is at your fingertips..right across the road and the little restaurant upstairs does a great breakfast (and a really good latte !!!) We used the laundrette in the hotel and it was clean and well lit - what more could you want.
This is a "family" hotel - nice and quiet with a relaxed air about it. We will definitely stay here again.', 1, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('stayed here for 4 nights in December. It is a great hotel, based in the upper East side, 5 minutes walk from central park. The staff were friendly and helpful. We stayed in a 2 bedroom suite which was very affordable and perfect for our family of four. The kitchen was an added bonus as there is a Supermarket across the way where you can get a wide range of food.', 0, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('My partner and I stayed here from 6th December - 10th December and had one of the best holidays ever! The beacon hotel was a fantastic place to stay with friendly and polite staff who could not do enough for you.
The rooms were modern, spacious and clean and the beds were heaven after a long day walking around manhattan.
The area of the hotel was ideal for us as it allowed us to see many of the New York attractions whilst keeping away from the hustle and bustle that many midtown hotels would experience.
The hotel itself is about a 10 minute walk from Central Park, however a 30/40 minute walk to many midtown attractions eg. Rockafella centre. I would advise the city bus tour which was $54 dollars per person as it allows you to see all of the main tourist attractions and helps you find your bearings (especially first timers)
Our overall experience of the beacon hotel and New York as a whole is 10 out of 10. I could not recommend the hotel enough!', 0, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('We enjoyed our stay at Hotel Beacon. We got a 1 BR suite, which worked out fine for our group of 3 on a girls'' trip. (There is a fold out couch in the living room). It was nice to have a refrigerator to store cold drinks, leftovers and breakfast items. The staff was very nice and responded quickly to requests for more towels, etc. The only issue we had was that one night there was a late concert going on at the Beacon Theater next door and from our room we could hear the music. 
The location is great....we liked being in a "neighborhood" and love the tree-lined side streets and brownstone homes nearby. In just a few blocks of walking (less than 5 minutes) you can be at a subway stop. I would definitely recommend Hotel Beacon for all kinds of travelers.', 0, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('Great hotel for New York. Kitchenette is a godsend and whilst small has everything you need. Our room was on 21st floor, and we compromised some space and bed size (we had initially been allocated 11th fl) for a fantastic view; and far more natural light. Room was cleaned daily and you can ask for extra kitchen things, like sharp knife (!!) wine glasses etc. Supermarket is just over the road.
We arrived on Thanksgiving and got excellent service from the check in manager and Kenny at the door was great. Other times it was not quite so good, or pleasant. And the information given out by the concierge regarding half tix booth downtown was incorrect. We ended up wasting half a day travelling downtown (which was closed due to Sandy) as a result. Not happy at all. 
Otherwise, all good - easy to get to subway, walk to Central Park and MNH, $10 cab ride to/from pretty much all the other major attractions.', 0, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('My best friend and I went to NYC in August last year and spent 2 weeks at Hotel Beacon. We booked the 1 bedroom, 2 double bed room. The room was HUGE, very clean and we had a great view. Our room had a coffee machine, which was re-stocked with coffee pods and creamer every day by the cleaning staff. There is also a great restaurant next door, the owner was very nice and makes an effort to greet his customers (and remembers the ones who go back multiple times like us!). 
My only complaints:
1. (I don''t know if this was an issue with our room only) - The bathroom didn''t have any sort of ventilation, so we had to shower with the door open or the whole room would steam up. This wasn''t a problem for us and wouldn''t really be a problem for a couple, but could get awkward if you were staying with your boss on a business trip!
2. No complimentary wireless internet - For the amount of money we paid, it would have been nice to have access to wifi, even if we had to sit in the lobby or something to get it. They have the option of around $10 per day to get wireless in the room, or you could go to the computer room which only had 2 computers in it (and it was always full). 
Overall - A great hotel. The staff were extremely friendly (especially the door men, who would happily stand and have a chat while we were waiting for a taxi), the room was lovely and it''s in a great spot (walking distance to Times Square or easy access to the subway for those who don''t want to walk). Would definitely recommend it to friends and family :)', 1, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('Regular visitor of this hotel,i believe is the best hotel in the best location...simple,clean,not crazy expensive,not noisy ,with great beds! and near to all the attractions that i wanted to visit.We always take the 1 bedroom suite,has a living room,a small kitchinette and a large bedroom.Very good value for money!', 0, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('We just returned from NYC after staying at the Beacon. This is our second stay. We have stayed in both the regular rooms with kitchen and the suites. Suites are great with two separate rooms, plenty of space, great bed, small kitchen and comfortable living room. Very well maintained and clean. Bathroom off the bedroom and well appointed. Staff is very attentive, especially the ladies who clean the rooms. (Leave a big tip) Very close to the 72nd street subway station and all the great attractions on the west side, including Central Park, Natural History Museum. Across the street is the Fairway Market, a jewel itself, to stock your kitchen at the Hotel. Beacon Liquors next store for that nice bottle of wine.Seems to have many international guests.You can pay a lot more money in NYC but you won''t do better.', 0, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('What an unexpected delight. The hotel suite was two separate rooms and was decorated in a lovely way. The kitchenette was nice with a full fridge. Only complaint is that there was no bottled water to buy or have as a guest amenity. Wonderful location near Columbus circle', 0, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('This was our second visit and we had two rooms -- one for us and the other for our guests, a family with two children. The Beacon is well located, 2 blocks to subway, an easy walk to Central Park and midtown. Rooms are large for NYC, nicely appointed and clean. Very friendly and helpful staff. Excellent value.', 1, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('My partner and I went on holiday to NYC on 27/10/12 (the day before Hurricane Sandy!!!!) and booked to stay at the Hotel Beacon. After reading previous reviews on here it was recommended that we emailed in advance to request a high corner room away from the lifts. I did choose to email in advance as I also wanted to inform the hotel that I was planning to propose to my girlfriend. I received a swift response from the reservations department and they were very polite. 
Upon arrival, our room wasn''t ready (we were two hours early) but the staff were very friendly and informative. They recommend a few local shops and food places if we wanted to pass the time. When we arrived back after just over an hour the room was ready and we were allocated a room on the 21st floor (there is only 25 floors in the hotel). I do not cope well with confined spaces etc but the speed of the lifts was excellent and I managed to survive the constant use! :). We arrived at our room and it appeared we had been given a larger room (possibly because I emailed in advance) and we also received a complimentary bottle of wine and box of chocolates which was a lovely touch. The room was excellent, large, spacious, very clean with more than enough storage. The views from our huge window were fantastic! The concierge were attentive and informative without being pushy (this was my partners 6th time in NYC and they did not feel the need to tell her anything as she had good local knowledge). 
Even though NYC pretty much shut down for a few days, the housekeeping service was still available (albeit on a reduced staff) and they were very polite. If you are there for a few nights (we were for 5) I would recommend that on your first morning to leave a $10 dollar tip and a note to housekeeping then leave $2/$3 for the duration of your stay and you will end up with plenty of extra toiletries/towels/pillows etc or anything else you may need. 
The hotel staff kept all guests up to date with information regarding local facilities that were still available during the hurricane. 
We were both very impressed with Hotel Beacon and the staff and will certainly be planning on staying there again when we visit again next year. It is extremely popular with a wide variety of ages and people visiting for various reasons. I highly recommend the Hotel Beacon.
P.S. my partner agreed to marry me when I proposed! I also received an email from the hotel to congratulate us.', 5, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('We needed a room at the last minute in Manhattan and got a very good rate from The Beacon. We were treated with great sympathy by the friendly efficient reception staff and subsequently found that helpful attitude was typical of all the staff we encountered.
The room was spacious and clean and surprisingly very quiet - no sounds could be heard from neighbouring rooms or the floor above.
The hotel is in a very good location- close to Lincoln Centre and Central Park, a couple of blocks from the subway. It seems to be a very busy family area and very safe. Lots of cafes,and restaurants and a fabulous supermarket across the street.
We would certainly return.', 0, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('I have stayed at this Hotel (which is a residence hotel) for over a dozen years. What brings me back for so long is the fabulous service and value. Mary at the front desk has been there longer that I have been going there. The entire staff is very attentive.
 When you stay here you are getting an apartment. I have experienced both the studio and the one bedroom units. All have been recently renovated. Basically we love this hotel and it''s location on the upper west side less that two blocks from the subway.', 1, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('Stayed at the Hotel Beacon over Veteran''s Day weekend and the experience could not have been better. This hotel is a block from the subway, clean, clean, clean and best of all for NYC, QUIET. The front desk was extremely helpful and we will stay here again. Pass up the Fairway market across the street and walk another block and a half north and visit the West Side Market for food, groceries, liquor, etc. And be sure and drop in next door to Big Nick''s pizza for a slice, delicious and cheap! The Hotel Beacon also has a small kitchenette with refrig if you require one. This is a wonderful hotel, don''t even think about staying at the hotels around Times Square.', 3, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('We are from Australia and stayed here for 9 days. We were worried at first that it was too far from Times Square, but in fact it is the perfect location to stay. It is situated in the Upper West side district which is very family and "Dog" friendly. We saw 10 musicals in 9 days and travelling late at night was not a problem at all. Just a 3minute walk to the subway and get on the 2 or 3 express train downtown which takes 3 minutes and you are in Times Square. One more stop and you are in 34th Street at Macy''s. The hotel itself was excellent. Very friendly staff who will help you with any question. The room was big with the kitchenette. The bed was very comfortable.
You can also choose to eat junk food or very healthy as there are numerous gourmet supermarkets across the road which are so much better than Coles or Woolworths. Down the raod is "Big Nicks" diner which is open late at night after the theatre has finished. 
When travelling on the subway get the $29.00 seven day pass. You can see all of the New York sights via the subway. The subway is very easy to use as well. Took no time to pick it up.
Walk the streets around here and you will find some lovely boutiques which are way cheaper than prices in Australia. Overall a great quiet district to stay in away from the hussle and bussle of Times Square.', 2, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('Stayed here while visiting carnegie hall show. Rooms are very clean, bright colors, welcoming,small bathroom but everything worked. In room coffee, little kitchenette. Tv didn''t work but it was only for checking the news, so not a big issue.bed and linens were very comfortable. Will stay here again.', 2, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('We were a group of 4 adults and 3 children so we booked 2 1 bedroom suites which were perfect. The bedrooms were spacious and the lounge area had a lot of room to move around, even once you put the sofa bed up. The kitchen is small but adequate and when staying for 6 nights it was nice to be able to make breakfasts and heat things up for dinner. There was lots of storage space so we weren''t tripping over our cases. The only thing which could be improved would be to have more hooks to hang towels in the bathroom but aside from that we were extremely happy with the Beacon. The staff were friendly and helpful and the rooms clean. The location was excellent. Fairways market was across the road for breakfast supplies and there were lots of restaurants and cafes within a short walk. The subway station was a two minute walk and it was only a 5 minute walk to Central Park and a 25 min walk to Times Square. Was really nice to be in a residential area that was quiet, yet close to everything. Will definately stay at the Beacon when we come back to New York.', 1, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('Excecllent for families as you can get suites with one or two bedrooms. We travelled as a family of four and had a one bedroom suite - the pull out sofabed in the living room were great fofr the kids and folded up in seconds in the morning. Small kitchen area with fridge and gas stove - the only negative thing really was that the gas stove was just too easy to switch on by accident - several times we must have touched it without realizing what was happening and could suddenly smell gas... Friendly staff and just metres away from the 72nd street subway station. Fairways market across the road provided us with breakfast. A handy Duane Reade (pharmacy, beauty products and snacks) vvery close - open 24/7. Starbucks at hand :)', 1, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('We stayed here for only one night but wish it had been longer. The location of the hotel was perfect for our family of 4 ... we were able to walk to the Park, Central Park Zoo, FAO Schwarz, and, most importantly,Gray''s Papaya! The staff was very accommodating; we were arriving from a hotel in Brooklyn and when I contacted this hotel, they allowed for an early check-in. The one-room suite was ideal for us with our two younger boys (5, 8) and the kitchen area was was perfect. The room was very clean; the bed was very comfortable; and the hotel was very quiet. We didn''t hear a peep from anyone else in the hotel! We will DEFINITELY stay here again.', 1, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('We stayed here the week before Thanksgiving 2012. We were on the 25th floor facing Central Park. The room was much bigger than we expected for NYC. We didn''t hear any street noise in our room thanks to the soundproof glass. Noise from other rooms was minimal. We had a king sized bed and a kitchenette. There are a few grocery stores within walking distance, so we bought breakfast foods to save a few dollars during our stay. The neighborhood is great and the staff was friendly. The subway is close and if you want to hoof it Central Park and Times Square are walkable if you have plenty of time and good shoes. We will use the Hotel Beacon again.', 0, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('Great location for our Thanksgiving weekend festivities; 2.5 blocks from Central Park West where we camped out for the parade. (Getting there at 6am was not early enough for front row, fyi! Next time: 5 am). Our 2 room King suite was spacious (for NYC), the kitchenette well equipped; the bathroom had a great powerful shower with plenty of hot water (but no exhaust fan - got pretty steamy with 3 adults showering in a row). Very nice furnishings, clean and well-maintained. 2 big TVs; docking station for iPods. Our low-floor room was great given that the elevators can be slow. I never knew about the laundry room that others have mentioned here; I add that to the list of things the staff couldn''t be bothered with telling us. Along with: no parking garage within 10 blocks will let you park overnight over Thanksgiving (we ended up at Lincoln Center 12 blocks away, on a tip from a guy at the 6th garage we tried); even though checkin is at 3pm, that doesn''t necessarily mean 3, it might mean 4:30; (because "it''s really busy" - now I know to only expect what I pay for when it''s slow). I know it''s been a while since I''ve been to NY, because I noticed the lack of pleasantries, such as "good morning" from a doorman or "Did you enjoy you stay?" from the front desk. Ah well. It''s a nice place and you''ll love it if you want to stay in a quieter part of the city, without being too far away from things. Fairway across the street; Starbucks on the corner; liquor store next door. Perfect for our 3 day stay :)', 0, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('Stayed here from 23 Sep until the 27 Sep 2012. Wonderful hotel! Conveniently located close to the subway, which was awesome as we bought a week subway pass and used the subway for all our transport requirements. Arrived at the hotel really early in the morning at 8am, the staff were wonderful and checked us in at 12pm instead of 3pm. The hotel room was amazing we stayed in a one bedroomed suite, which suited our needs perfectly. The room had a small kitchen, lounge, bedroom, bathroom and dining area. Really spacious for NYC. I would definitely recommend this hotel and stay there again. The only complaint was that we we so busy and did not have enough time to spend in the room.', 1, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('We stayed here recently on our honeymoon. We loved it! The room was a great size and had an incredible view of the building of the upper west side. Location was excellent and only a short walk to the nearest subway station and quite a few fantastic restaurants. The only negative was the bathroom. It was a good size but it was very dated and the grout etc was quite yellow and old also the shower was a bit odd at times with water pressure. That being said, it wasn''t a major problem for us anyway.', 1, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('We were planning to stay 7 nights however it turned into 11 courtesy of Hurricane Sandy. This hotel is brilliantly located on the upper west side a couple of blocks back from Central Park. The subway at 72nd street is a short walk away and this station gives you the option of express trains to 42nd Street and beyond making it incredibly fast to get anywhere downtown. We also walked to and from 34th Street quite comfortably on a number of occassions.
The hotel itself is very nice and we were surprised at how quiet it was. Having a small kitchenette was a bonus that allowed us to eat in on a number of occasions from the extensive food market across the street. The diner next door was excellent for breakfast.
The staff are New Yorkers so their style is somewhat different from what you generally see in a hotel of this standard, but after 11 days even I was starting to act like a New Yorker. If you don''t know what I mean then this will be one of the great things you can discover on your visit to this brilliant city.', 3, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
INSERT INTO reviews 
            VALUE('If staying on the Upper West Side, you can''t go wrong here. The rooms were very clean, great decor, comfortable beds and linens. We were fortunate enough to get a suite and it felt as if we were staying in an apartment in the city. My daughters were thrilled to see what it would be like to live in NYC as opposed to the very tourist oriented areas of the city. There is a nice laundry room that we used. I''m not sure that this is the area we would stay in next time, because it took a while to get to midtown attractions, but if we do return to the UWS, we will definitely be staying at the Beacon', 1, 'http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html', 'Hotel Beacon', 'New York City'
            );
